import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { RunContext } from '../context.js';
import type { RunOptions, Manifest, ImageQCReport, StoryPlan } from '../types.js';

const STEP = 'final_qc';

export async function finalQC(ctx: RunContext, opts: RunOptions): Promise<void> {
  ctx.log(STEP, 'info', 'start');
  void opts;

  const manifest: Manifest = JSON.parse(readFileSync(ctx.manifestPath, 'utf-8'));
  const qcReport: ImageQCReport = JSON.parse(
    readFileSync(join(ctx.dirs.images, 'image_qc.json'), 'utf-8'),
  );
  const plan: StoryPlan = JSON.parse(
    readFileSync(join(ctx.dirs.story, 'page_plan.json'), 'utf-8'),
  );

  const screenPDF = join(ctx.dirs.pdf, 'book_screen.pdf');
  const printPDF  = join(ctx.dirs.pdf, 'book_print.pdf');

  const screenSize = existsSync(screenPDF) ? statSync(screenPDF).size : 0;
  const printSize  = existsSync(printPDF)  ? statSync(printPDF).size  : 0;

  // ── Group artifacts by step ───────────────────────────────────────────────
  const byStep = new Map<string, number>();
  for (const a of manifest.artifacts) {
    byStep.set(a.step, (byStep.get(a.step) ?? 0) + 1);
  }
  const artifactTable = Array.from(byStep.entries())
    .map(([s, n]) => `| ${s.padEnd(26)} | ${String(n).padStart(3)} artifacts |`)
    .join('\n');

  const imagePassCount = qcReport.results.filter(r => r.passes).length;

  const report = `# Final QC Report

**Run ID:** \`${ctx.run_id}\`
**Completed:** ${new Date().toISOString()}

---

## Artifact Summary

| Step                       | Count       |
|---|---|
${artifactTable}

**Total artifacts:** ${manifest.artifacts.length}

---

## Story

| Field | Value |
|---|---|
| Title | ${plan.title} |
| Pages | ${plan.page_count} |

---

## Image QC

| Check | Result |
|---|---|
| Total pages checked | ${qcReport.total_pages} |
| Images passing all checks | ${imagePassCount} / ${qcReport.total_pages} |
| Minimum dimension enforced | ${qcReport.min_dimension_check}px |
| Overall pass | ${qcReport.all_pass ? '✓ YES' : '✗ NO'} |

${!qcReport.all_pass ? '**WARNING:** Some images failed QC. See `05_images/image_qc.json` for details.\n' : ''}

---

## PDF Output

| File | Size |
|---|---|
| \`07_pdf/book_screen.pdf\` | ${screenSize.toLocaleString()} bytes |
| \`07_pdf/book_print.pdf\`  | ${printSize.toLocaleString()} bytes |

${screenSize === 0 ? '**ERROR:** book_screen.pdf is empty or missing.\n' : ''}
${printSize  === 0 ? '**ERROR:** book_print.pdf is empty or missing.\n'  : ''}

---

## Validation Status

${[
  `- [ ] Real ASR (Phase 2)`,
  `- [ ] Real story writer / GPT-4o (Phase 2)`,
  `- [ ] Real image generation / SDXL (Phase 2)`,
  `- [x] Artifact manifest with SHA-256 hashes`,
  `- [x] Structured JSONL logs`,
  `- [x] PNG existence and header validation`,
  `- [x] PDF existence and magic-byte validation`,
  `- [x] Page count matches requested`,
].join('\n')}

---

*Generated by Babel Books v0.1.0 — Phase 1*
`;

  const reportPath = join(ctx.run_dir, 'final_report.md');
  writeFileSync(reportPath, report);
  ctx.addToManifest(reportPath, STEP, { type: 'final_report' });

  ctx.log(STEP, 'info', `done — report written to ${reportPath}`);
}
